# loading package
library(blockCV)
library(raster)
library(terra)
library(sf)
library(ggplot2)
library(caret)
library(Metrics)
library(caret)
library(randomForest)
library(spatialEco)
library(gstat)
library(lme4)
library(ggthemes)
library(readr)
library(dplyr)
library(RColorBrewer)

library(covWt)
library(scales)